## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [45]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [46]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('sigmoid', nn.Sigmoid()),    # sigmoid activation function
    ('output', nn.Linear(3, 2)),  # output layer with 2 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(10000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()
    # forward pass
    outputs1 = model1(data_in1)
    # calculate loss
    loss1 = criterion1(outputs1, data_target1)
    # backward pass
    loss1.backward()
    # update weights
    optimizer1.step()
    losses1.append(loss1.item())

    # accuracy
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break


# visualize the resuts
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')


# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 4
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[ 0.4123, -0.6766],
        [ 0.1021,  0.3456],
        [-0.6455,  0.0973]])
hidden.bias tensor([-0.3381,  0.6380,  0.4902])
output.weight tensor([[ 0.4959,  0.2903, -0.5675],
        [-0.2456, -0.0079,  0.1364]])
output.bias tensor([ 0.3330, -0.0015])


In [47]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('sigmoid', nn.Sigmoid())     # sigmoid activation function
]))

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

# visualize the results
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)



tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 298
tensor([[0.2742, 0.5000],
        [0.3408, 0.4868],
        [0.2950, 0.4957],
        [0.3840, 0.4789]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[ 0.4888, -0.2264],
        [-0.0198,  0.3840],
        [ 0.3584,  0.7608]])
hidden.bias tensor([-0.5569, -0.4647, -0.1624])
output.weight tensor([[-0.4523,  0.3053,  0.5266],
        [ 0.1008, -0.4131, -0.0889]])
output.bias tensor([-9.7462e-01,  2.5743e-04])


In [48]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),  # first hidden layer with 3 neurons
    ('ReLU', nn.ReLU()),          # relu activation function
    ('output', nn.Linear(3, 2)),  # output layer with 3 neurons
    ('tanh', nn.Tanh())     # sigmoid activation function
]))

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

# train the model
losses1 = []
for epoch in range(1000):
    # reset the gradients to zero before each forward and backward pass
    optimizer1.zero_grad()
    outputs1 = model1(data_in1) # forward pass
    loss1 = criterion1(outputs1, data_target1) # calculate loss
    loss1.backward()          # backward pass
    optimizer1.step()         # update weights
    losses1.append(loss1.item())
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.sum().item() / len(data_target1)
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

# visualize the results
print(outputs1)
predicted = torch.round(outputs1)
correct = (predicted == data_target1).sum()
total = data_target1.size(0)
accuracy = correct / total
print(f'Model Accuracy: {accuracy}%')

# print model wights
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Model 1 reached 100% accuracy at epoch 4
tensor([[-0.2733, -0.4287],
        [-0.2532, -0.5218],
        [-0.0178, -0.4350],
        [ 0.0038, -0.5274]], grad_fn=<TanhBackward0>)
Model Accuracy: 1.0%
Model weights:
hidden.weight tensor([[-0.0371,  0.1136],
        [ 0.2278,  0.2114],
        [-0.4153,  0.3724]])
hidden.bias tensor([0.4258, 0.1799, 0.5295])
output.weight tensor([[ 0.3904,  0.6136, -0.3377],
        [-0.1301, -0.2483, -0.0785]])
output.bias tensor([-0.3080, -0.1983])
